"""Add driver fields to Ride model

Revision ID: add377f389fc
Revises: 
Create Date: 2026-08-01 02:31:21.573233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add377f389fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('counter_offer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('rider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pickup',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('fare_offer',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_foreign_key(
    "fk_ride_driver",
    "user",
    ["driver_id"],
    ["id"]
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(
    "fk_ride_driver",
    type_="foreignkey"
)
        batch_op.alter_column('fare_offer',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('destination',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('pickup',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('rider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('counter_offer')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
